/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.example.kafkaproject.event;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class OrderCreatedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1070296987239446686L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"OrderCreatedEvent\",\"namespace\":\"org.example.kafkaproject.event\",\"fields\":[{\"name\":\"orderedItems\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"ProductDTO\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"productId\",\"type\":\"long\"},{\"name\":\"productName\",\"type\":\"string\"},{\"name\":\"quantity\",\"type\":\"long\"}]}},\"default\":[]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<OrderCreatedEvent> ENCODER =
      new BinaryMessageEncoder<OrderCreatedEvent>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<OrderCreatedEvent> DECODER =
      new BinaryMessageDecoder<OrderCreatedEvent>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<OrderCreatedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<OrderCreatedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<OrderCreatedEvent>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this OrderCreatedEvent to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a OrderCreatedEvent from a ByteBuffer. */
  public static OrderCreatedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.util.List<org.example.kafkaproject.event.ProductDTO> orderedItems;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public OrderCreatedEvent() {}

  /**
   * All-args constructor.
   * @param orderedItems The new value for orderedItems
   */
  public OrderCreatedEvent(java.util.List<org.example.kafkaproject.event.ProductDTO> orderedItems) {
    this.orderedItems = orderedItems;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return orderedItems;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: orderedItems = (java.util.List<org.example.kafkaproject.event.ProductDTO>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'orderedItems' field.
   * @return The value of the 'orderedItems' field.
   */
  public java.util.List<org.example.kafkaproject.event.ProductDTO> getOrderedItems() {
    return orderedItems;
  }

  /**
   * Sets the value of the 'orderedItems' field.
   * @param value the value to set.
   */
  public void setOrderedItems(java.util.List<org.example.kafkaproject.event.ProductDTO> value) {
    this.orderedItems = value;
  }

  /**
   * Creates a new OrderCreatedEvent RecordBuilder.
   * @return A new OrderCreatedEvent RecordBuilder
   */
  public static org.example.kafkaproject.event.OrderCreatedEvent.Builder newBuilder() {
    return new org.example.kafkaproject.event.OrderCreatedEvent.Builder();
  }

  /**
   * Creates a new OrderCreatedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new OrderCreatedEvent RecordBuilder
   */
  public static org.example.kafkaproject.event.OrderCreatedEvent.Builder newBuilder(org.example.kafkaproject.event.OrderCreatedEvent.Builder other) {
    return new org.example.kafkaproject.event.OrderCreatedEvent.Builder(other);
  }

  /**
   * Creates a new OrderCreatedEvent RecordBuilder by copying an existing OrderCreatedEvent instance.
   * @param other The existing instance to copy.
   * @return A new OrderCreatedEvent RecordBuilder
   */
  public static org.example.kafkaproject.event.OrderCreatedEvent.Builder newBuilder(org.example.kafkaproject.event.OrderCreatedEvent other) {
    return new org.example.kafkaproject.event.OrderCreatedEvent.Builder(other);
  }

  /**
   * RecordBuilder for OrderCreatedEvent instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<OrderCreatedEvent>
    implements org.apache.avro.data.RecordBuilder<OrderCreatedEvent> {

    private java.util.List<org.example.kafkaproject.event.ProductDTO> orderedItems;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.example.kafkaproject.event.OrderCreatedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.orderedItems)) {
        this.orderedItems = data().deepCopy(fields()[0].schema(), other.orderedItems);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing OrderCreatedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(org.example.kafkaproject.event.OrderCreatedEvent other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.orderedItems)) {
        this.orderedItems = data().deepCopy(fields()[0].schema(), other.orderedItems);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'orderedItems' field.
      * @return The value.
      */
    public java.util.List<org.example.kafkaproject.event.ProductDTO> getOrderedItems() {
      return orderedItems;
    }

    /**
      * Sets the value of the 'orderedItems' field.
      * @param value The value of 'orderedItems'.
      * @return This builder.
      */
    public org.example.kafkaproject.event.OrderCreatedEvent.Builder setOrderedItems(java.util.List<org.example.kafkaproject.event.ProductDTO> value) {
      validate(fields()[0], value);
      this.orderedItems = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'orderedItems' field has been set.
      * @return True if the 'orderedItems' field has been set, false otherwise.
      */
    public boolean hasOrderedItems() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'orderedItems' field.
      * @return This builder.
      */
    public org.example.kafkaproject.event.OrderCreatedEvent.Builder clearOrderedItems() {
      orderedItems = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public OrderCreatedEvent build() {
      try {
        OrderCreatedEvent record = new OrderCreatedEvent();
        record.orderedItems = fieldSetFlags()[0] ? this.orderedItems : (java.util.List<org.example.kafkaproject.event.ProductDTO>) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<OrderCreatedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<OrderCreatedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<OrderCreatedEvent>
    READER$ = (org.apache.avro.io.DatumReader<OrderCreatedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
